### ISSUE TITLE
get error. Traceback (most recent call last): File "/home/pi/PiClock/Clock/PyQtPiClock.py", line 15, in import dateutil.parser ModuleNotFoundError: No module named 'dateutil'

### ISSUE THREAD

**Issue by lstew452a** [n0bel/PiClock#232]
I had to re-install the OS n my raspberry pi and when run PIClock I get error. Traceback (most recent call last):
File "/home/pi/PiClock/Clock/PyQtPiClock.py", line 15, in
import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

**Comment by lstew452a** [comment]
All fixed. I sudo pip3 install tzlocal.
